import streamlit as st
import os
from dotenv import load_dotenv
from openai import OpenAI
import tiktoken
from helper_functions.utility import check_password

load_dotenv('.env')

client = OpenAI(api_key=os.getenv('OPENAI_API_KEY'))

# region <--------- Streamlit App Configuration --------->
st.set_page_config(
    layout="centered",
    page_title="My Streamlit App"
)
# endregion <--------- Streamlit App Configuration --------->


st.title("Streamlit App")

form = st.form(key="form")
form.subheader("Prompt")

user_prompt = form.text_area("Enter your prompt here", height=200)

if form.form_submit_button("Submit"):
    st.toast(f"User Input Submitted - {user_prompt}")
    response = "Hello" # <--- This calls the helper function that we have created 🆕
    st.write(response) # <--- This displays the response generated by the LLM onto the frontend 🆕
    print(f"User Input is {user_prompt}")

if not check_password():
    st.stop()
